use crate::Target;

pub fn generate_skeleton(
    chip_name: &str,
    target: &Target,
    features: Vec<String>,
    version: &str
) -> String {
    let mut skeleton = String::new();

    skeleton += &generate_header(chip_name, version);
    skeleton += &generate_dependencies(target);
    skeleton += &generate_profiles();
    skeleton += &generate_features(target, features);

    skeleton
}

fn generate_header(chip: &str, version: &str) -> String {
    format!("# Automatically generated by svd2rust {version}
[package]
name = \"{chip}-pac\"
keywords = [\"no-std\", \"embedded-hal\"]
version = \"0.1.0\"
authors = []
# edition = \"2018\"
",
        chip=chip,
        version=version
    )
}

fn generate_dependencies(target: &Target) -> String {
    let mut deps = String::new();
    deps += "\n";
    deps += "[dependencies]\n";
    deps += "vcell = \"0.1.0\"\n";

    match target {
        Target::CortexM => {
            deps += "bare-metal = \"0.2.0\"\n";
            deps += "cortex-m = \"0.5.0\"\n";
            deps += "
[dependencies.cortex-m-rt]
optional = true
version = \"0.5.0\"
";
        }
        Target::Msp430 => {
            deps += "bare-metal = \"0.1.0\"\n";
            deps += "msp430 = \"0.1.0\"\n";
            deps += "msp430-rt = \"0.1.0\"\n";
        }
        Target::RISCV => {
            deps += "bare-metal = \"0.1.0\"\n";
            deps += "riscv = \"0.2.0\"\n";
            deps += "riscv-rt = \"0.2.0\"\n";
        }
        Target::None => {
            // No dependencies
        }
    }

    deps
}

fn generate_profiles() -> String {
    let mut out = String::new();
    out += "\n";
    out += "[profile.dev]\n";
    out += "incremental = false\n";
    out += "\n";

    out
}

fn generate_features(target: &Target, features: Vec<String>) -> String {
    let mut out = format!(
        "
[features]

# Auto generated feature flags
# By default, NO peripherals are enabled for use. To activate peripherals, select
# each peripheral (as a feature flag) necessary for your use, or select the `all`
# feature to activate all peripherals (selecting all will increase compile time)
all = [ {} ]

default = []
",
        features.iter().map(|feat| format!("'{}'", feat)).collect::<Vec<_>>().join(", "),
    );

    match target {
        Target::CortexM => {
            out += "rt = [\"cortex-m-rt/device\"]\n";
        }
        Target::Msp430 => {
            out += "rt = [\"msp430-rt/device\"]\n";
        }
        Target::RISCV => {
            out += "rt = [\"riscv-rt/device\"]\n";
        }
        Target::None => {},
    };

    out += "\n";
    out += "# Individual Peripherals\n";
    out += &features.iter().fold(String::new(), |mut s, f| {
            s.push_str(&format!("{} = []\n", f));
            s
    });

    out
}
